# Generated by Django 5.0.4 on 2024-04-20 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PerformerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="имя")),
                (
                    "surname",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="фамилия"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Номер телефона должен начинаться с символа  и содержать 9-15 цифр",
                                regex="^\\+\\d{9,15}$",
                            )
                        ],
                        verbose_name="номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        unique=True,
                        verbose_name="почта",
                    ),
                ),
                (
                    "experience",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="опыт в годах"
                    ),
                ),
            ],
            options={
                "verbose_name": "исполнитель",
                "verbose_name_plural": "исполнители",
            },
        ),
    ]
