# Generated by Django 5.0.4 on 2024-04-20 10:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, unique=True, verbose_name="почта"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="experience",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="опыт в годах"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message='Phone number should start from "+" and consists of 9-15 digits',
                        regex="^\\+\\d{9,15}$",
                    )
                ],
                verbose_name="phone",
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="surname",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="фамилия"
            ),
        ),
    ]
