# Generated by Django 5.0.4 on 2024-04-20 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_customer_email_customer_experience_customer_phone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"verbose_name": "заказчик", "verbose_name_plural": "заказчики"},
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Номер телефона должен начинаться с символа  и содержать 9-15 цифр",
                        regex="^\\+\\d{9,15}$",
                    )
                ],
                verbose_name="номер телефона",
            ),
        ),
    ]
